// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6UeULAS_in-cnjGBJLg2-EvQdE9zYXo',
    appId: '1:99088554709:web:1245d686ff61691d2ae05c',
    messagingSenderId: '99088554709',
    projectId: 'phoneverification-b567a',
    authDomain: 'phoneverification-b567a.firebaseapp.com',
    databaseURL: 'https://phoneverification-b567a-default-rtdb.firebaseio.com',
    storageBucket: 'phoneverification-b567a.appspot.com',
    measurementId: 'G-H6Q87FH2FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6RJ7q0BJ2ah-d3Bz_6r3xk5pEkuJPYs',
    appId: '1:99088554709:android:9c1fe07065a6d0632ae05c',
    messagingSenderId: '99088554709',
    projectId: 'phoneverification-b567a',
    databaseURL: 'https://phoneverification-b567a-default-rtdb.firebaseio.com',
    storageBucket: 'phoneverification-b567a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkibDqsijJSXg7kW1X1N2IrEEVRGY5Plo',
    appId: '1:99088554709:ios:7f552a18536652b52ae05c',
    messagingSenderId: '99088554709',
    projectId: 'phoneverification-b567a',
    databaseURL: 'https://phoneverification-b567a-default-rtdb.firebaseio.com',
    storageBucket: 'phoneverification-b567a.appspot.com',
    androidClientId: '99088554709-jc4f37eao6f1tgmt0pf2gs3svvba2v7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkibDqsijJSXg7kW1X1N2IrEEVRGY5Plo',
    appId: '1:99088554709:ios:7f552a18536652b52ae05c',
    messagingSenderId: '99088554709',
    projectId: 'phoneverification-b567a',
    databaseURL: 'https://phoneverification-b567a-default-rtdb.firebaseio.com',
    storageBucket: 'phoneverification-b567a.appspot.com',
    androidClientId: '99088554709-jc4f37eao6f1tgmt0pf2gs3svvba2v7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY6UeULAS_in-cnjGBJLg2-EvQdE9zYXo',
    appId: '1:99088554709:web:3b32d0a883e708632ae05c',
    messagingSenderId: '99088554709',
    projectId: 'phoneverification-b567a',
    authDomain: 'phoneverification-b567a.firebaseapp.com',
    databaseURL: 'https://phoneverification-b567a-default-rtdb.firebaseio.com',
    storageBucket: 'phoneverification-b567a.appspot.com',
    measurementId: 'G-BG93VH8PZ1',
  );
}
